# plabar config
[plabar]
# global settings go here

# dimensions of the bar
width = 2256
height = 32
background_color = #000000
position = "bottom"

[block]
position = 0
color = #FF7236
width = 500


[text]

position = 0
color = #FFFFFF
font-face = "Worm Writing Mono 15" 
text = "10.4GiB of 900.0GiB free"

[block]
position = 2000
color = #FF7236
width = 256



